name: Release

permissions:
  contents: read
  checks: write

on:
  pull_request:
    branches:
      - 'releases/**'
      - 'main'
      - 'ci'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Increase Docker default shared memory
        run: |
          sudo jq '. + {"default-shm-size": "2G"}' /etc/docker/daemon.json > /tmp/daemon.json \
            || echo '{"default-shm-size": "2G"}' > /tmp/daemon.json
          sudo mv /tmp/daemon.json /etc/docker/daemon.json
          sudo systemctl restart docker
          docker run --rm alpine df -h /dev/shm

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneLinux64

      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
